# Change these first
owner: abpframework # Your GitHub organization or username, where this repository lives
repo: abpio-status # The name of this repository

sites:
  - name: abp.io
    url: https://abp.io/health-status
  - name: community.abp.io
    url: https://community.abp.io/health-status
  - name: commercial.abp.io
    url: https://commercial.abp.io/health-status
  - name: nuget.abp.io
    # url: https://nuget.abp.io/health-status
    url: https://nuget.abp.io/$API_KEY/v3/package/Volo.Abp.Account.Pro.Public.Web/7.0.0/Volo.Abp.Account.Pro.Public.Web.7.0.0.nupkg
  - name: docs.abp.io
    url: https://docs.abp.io/health-status
  - name: support.abp.io
    url: https://support.abp.io/health-status
  - name: blog.abp.io
    url: https://blog.abp.io/health-status
  - name: commercial-demo.abp.io
    url: https://commercial-demo.abp.io/health-status

assignees: # Users to assign downtime issues (optional)
  - skoc10

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.abp.io
  # baseUrl: /abpio-status
  logoUrl: https://commercial.abp.io/assets/svg/abp-logo-light.svg
  favicon: https://raw.githubusercontent.com/abpframework/abpio-status/master/assets/abp-logo-without-text.svg
  faviconSvg: https://raw.githubusercontent.com/abpframework/abpio-status/master/assets/abp-logo-without-text.svg
  name: " "    #abp.io status page
  introTitle: "**abp.io status page**"
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
