# Change these first
owner: abpframework # Your GitHub organization or username, where this repository lives
repo: abpio-status # The name of this repository

sites:
  - name: abp.io
    url: https://abp.io
  - name: community.abp.io
    url: https://community.abp.io
  - name: commercial.abp.io
    url: https://commercial.abp.io
  - name: nuget.abp.io
    url: https://nuget.abp.io
  - name: docs.abp.io
    url: https://docs.abp.io
  - name: support.abp.io
    url: https://support.abp.io
  - name: blog.abp.io
    url: https://blog.abp.io
  - name: commercial-demo.abp.io
    url: https://commercial-demo.abp.io

assignees: # Users to assign downtime issues (optional)
  - skoc10

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: st.abp.io
  baseUrl: /abpio-status
  logoUrl: https://commercial.abp.io/assets/svg/abp-logo.svg
  name: abp.io status
  introTitle: "**ABP.IO status page**"
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
